# This is a basic workflow to help you get started with Actions

name: execute

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: 
  #push:
  #  branches:
  #  - master
  schedule:
  # Run on the first of every month at 4:00 UTC
  - cron: "0 4 1 * *"


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Donate to the Electronic Freedom Foundation with executor funds going to the Tor Project.
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: "16.x"
    - run: npm i bitcoin-cash-forever
    - run: npx bitcoin-cash-forever --decay 300 --address bitcoincash:qqfchsuemty20rfyqsp2djjwxqhk6gw5av9v7wexjz --exAddress bitcoincash:qrtyy8w9yv6ffqtny9gp56m8kztl3nwwzcqyzsv32k --fee 1000
